/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package germanlabtool;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.text.BadLocationException;

/**
 *
 * @author markymark1346
 */
public class QueryUI extends javax.swing.JFrame {

    /**
     * Creates new form QueryUI
     */
    private QueryHandler theHandler;
    public QueryUI() {
        theHandler = new QueryHandler();
        initComponents();
        this.setTitle("German Lab Tool");
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputEditorPane = new javax.swing.JEditorPane();
        textInputLabel = new javax.swing.JLabel();
        textOutputLabel = new javax.swing.JLabel();
        stanfordConvertButton = new javax.swing.JButton();
        conllConvertButton = new javax.swing.JButton();
        loadELANButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jScrollPane1.setViewportView(inputEditorPane);

        textInputLabel.setText("Text Input");

        textOutputLabel.setText("Text Output");

        stanfordConvertButton.setText("Stanford Convert");
        stanfordConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stanfordConvertButtonActionPerformed(evt);
            }
        });

        conllConvertButton.setText("CONLL Convert");
        conllConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conllConvertButtonActionPerformed(evt);
            }
        });

        loadELANButton.setText("Load ELAN File");
        loadELANButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadELANButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(outputEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(textInputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textOutputLabel)
                                .addGap(192, 192, 192))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(198, Short.MAX_VALUE)
                        .addComponent(loadELANButton)
                        .addGap(113, 113, 113)
                        .addComponent(stanfordConvertButton)
                        .addGap(140, 140, 140)
                        .addComponent(conllConvertButton)
                        .addGap(117, 117, 117)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInputLabel)
                    .addComponent(textOutputLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conllConvertButton)
                    .addComponent(loadELANButton)
                    .addComponent(stanfordConvertButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadELANButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadELANButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser;
        fileChooser = new JFileChooser();     
        File f = new File(System.getProperty("user.dir"));
        fileChooser.setCurrentDirectory(f);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.showOpenDialog(this);
        File selectedFile = fileChooser.getSelectedFile();
        String theFileText = theHandler.loadELANFile(selectedFile);
        System.out.println(theFileText);
        //inputEditorPane.add(theFileText, inputEditorPane);
        try {
            inputEditorPane.getDocument().insertString(0, theFileText, null);
            //inputEditorPane.getDocument().insertString(0, "ham is good", null);
        } catch (BadLocationException ex) {
            Logger.getLogger(QueryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadELANButtonActionPerformed

    private void stanfordConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stanfordConvertButtonActionPerformed
        JFileChooser fileChooser;
        fileChooser = new JFileChooser();     
        File f = new File(System.getProperty("user.dir"));
        fileChooser.setCurrentDirectory(f);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.showOpenDialog(this);
        File selectedFile = fileChooser.getSelectedFile();
        String theConvertedText = "test";
        try {
            theConvertedText = theHandler.convertToStanford(selectedFile);
        } catch (IOException ex) {
            Logger.getLogger(QueryUI.class.getName()).log(Level.SEVERE, null, ex);
        } 
        try {
            outputEditorPane.getDocument().insertString(0, "Done! Check Log for output!", null);
            //outputEditorPane.getDocument().insertString(0, theConvertedText, null);
        } catch (BadLocationException ex) {
            Logger.getLogger(QueryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(theConvertedText);



    }//GEN-LAST:event_stanfordConvertButtonActionPerformed

    private void conllConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conllConvertButtonActionPerformed
        try {
            // TODO add your handling code here:
            theHandler.convertToCONLL();
        } catch (IOException ex) {
            Logger.getLogger(QueryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_conllConvertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conllConvertButton;
    private javax.swing.JEditorPane inputEditorPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadELANButton;
    private javax.swing.JEditorPane outputEditorPane;
    private javax.swing.JButton stanfordConvertButton;
    private javax.swing.JLabel textInputLabel;
    private javax.swing.JLabel textOutputLabel;
    // End of variables declaration//GEN-END:variables
}
